### ISSUE TITLE
Jump to a new layout

### ISSUE THREAD

**Issue by nguyenLisa** [gapran/prototypeJS#1]
See https://github.com/gapran/sim_platform/issues/39

**Comment by rashmigupta1709** [comment]
Reference : https://www.w3schools.com/jsref/met_win_open.asp

**Comment by rashmigupta1709** [comment]
window.open(URL, name, specs, replace)

**Comment by nguyenLisa** [comment]
28cf724fe7e843a4a63dacd204b96acbb16b42b5
