### ISSUE TITLE
Graph elements

### ISSUE THREAD

**Issue by nguyenLisa** [gapran/prototypeJS#2]
See https://github.com/gapran/sim_platform/issues/14

**Comment by rashmigupta1709** [comment]
I have used open source library for Charts. If you want to use any of the charts that are present in the library, we can simply pass and the data . The documentation with example is given at (https://www.chartjs.org/samples/latest/)

Also, example is implemented in client/imports/ui/barGraphs folder

**Comment by nguyenLisa** [comment]
f2ddd4290531348eca00439ca319f96274d5c9e9
