### ISSUE TITLE
bug on graph , after resizing the window the size of the graph will change

### ISSUE THREAD

**Issue by osamic** [gapran/prototypeJS#24]

**Comment by osamic** [comment]
![graph](https://user-images.githubusercontent.com/45318639/59279585-78093b80-8c64-11e9-8bdd-6a9dc03b2f00.PNG)

**Comment by nguyenLisa** [comment]
Workaround: 64a229258bf860cfbed583d925783926bd801ae8

**Comment by nguyenLisa** [comment]
22ea9caaea552ae26fde2f63e29b9e8737f2a940
