### ISSUE TITLE
Integrate IDE layout 

### ISSUE THREAD

**Issue by ghost** [gapran/prototypeJS#36]
This is part of **Issue** #10.
 
- [x] Add hi definition IDE like container
- [x] Integrate with gui elements present so far ( badge, progress, table, filter, tabs )

**Example**: 

![image](https://user-images.githubusercontent.com/17321286/60099031-21692a80-9757-11e9-9791-fd6af0590300.png)

**Comment by nguyenLisa** [comment]
6942fbdf605cf797025976cf185b714fea82912a
