### ISSUE TITLE
Filter element

### ISSUE THREAD

**Issue by nguyenLisa** [gapran/prototypeJS#4]
See https://github.com/gapran/sim_platform/issues/10

**Comment by rashmigupta1709** [comment]
For Filtering the data, database needs to be called.  Please check when you want the data to be filtered, specify when you will trigger the function and what needs to be returned .
For example : if you want to filter based on name , do you want to retrieve an object or a variable.
Also, when are you going to filter it ( onclick of a button or when you enter name )

**Comment by nguyenLisa** [comment]
1d655ccfd655b3474c25b8e8f9c640d9104bf4a6
