### ISSUE TITLE
data not being displayed in the table on the new page after clicking the button for new page

### ISSUE THREAD

**Issue by osamic** [gapran/prototypeJS#46]
![bug](https://user-images.githubusercontent.com/45318639/60896488-b5aeb380-a266-11e9-9a38-2553b83fd13d.PNG)

**Comment by nguyenLisa** [comment]
Hi @osamic , where is the branch in which you have this problem?

**Comment by nguyenLisa** [comment]
Could not reprodcuce the issue. Table works fine for prototype1.
Make sure that you address the correct template in the .js for your second page. For example in https://github.com/gapran/prototypeJS/blob/develop/imports/ui/prototype1/about.js#L11 the table data is populated to template prototype1_about and not to prototype1.
